### ISSUE TITLE
multiple invites to same call group prevent calls to this group

### ISSUE THREAD

**Issue by Florz** [eventphone/guru3#10]
**Problem:**
If two users open `extensions/invite` simultaneously, they can invite the same extension twice. This can also be forced by one group admin, by sending the same request multiple times.
If the user accepts these invites, he can not call the group anymore, because it is signaled as busy.

**Solution:**
Filter requests on the server and check if an extension is already a member of this group.

**Comment by thomasDOTwtf** [comment]
Hey Florz,
thanks for your feedback!
We already recognized the problem as it also causes a freeze in the sync between guru3 and our pbx. We'll keep you updated as soon as there is a fixed version online.
Thomas

**Comment by garw** [comment]
fixed
