### ISSUE TITLE
Add a new admin to call group, does not work

### ISSUE THREAD

**Issue by 2007M4N** [eventphone/guru3#11]
**Describe the bug**
when I want to add ad new admin to a "Call Group" => "Add call group for ..."
I land at the page, "Create a new call group" instead.

**To Reproduce**
1. Go to "My Call Groups"
2. Click on Actions "call group admins", from an existing Call Group
3. There is the site: "Admins for call group"
4. Click on "Add a new admin to call group"
   "https://guru3.eventphone.de/callgroup.htaccess/482/admin/new?environment=production"
5. See the wrong page: "Create a new call group"

**Expected behavior**
There should be a site to add admins to the callgroup

**Comment by zivillian** [comment]
@2007M4N Thanks for reporting this - should be fixed.
