### ISSUE TITLE
Adding (own) private extensions to call groups

### ISSUE THREAD

**Issue by MichiK** [eventphone/guru3#12]
**Is your feature request related to a problem? Please describe.**
Currently, extensions added to call groups need to be public. This gets tedious in case of call groups that should include a lot of non-public numbers (like in Heaven) as each number needs to be made visible, then they need to be added to the call group and then made invisible again.

**Describe the solution you'd like**
The dropdown list of extensions to add to a call group should contain not only all public extensions but also all own private extensions (preferably, all own extensions should show up at the top of the list as well).

**Comment by aveao** [comment]
I don't see why all numbers don't show up, private or public, regardless of who owns it. Phonebook may not show them, but it is still visible that it's occupied when you look at list of available extensions.

**Comment by jfwiebe** [comment]
I ran across the same issue today. Maybe show the "Orga Phonebook" in the dropdown, if the user is allowed to view it.

**Comment by garw** [comment]
fixed
