### ISSUE TITLE
In the invoice PDF, page number generation in the footer does not work. 

### ISSUE THREAD

**Issue by Kuermel** [eventphone/guru3#21]
**Describe the bug**
In the invoice PDF, page number generation in the footer does not work. 

"Page {{ current_page }} of undefined"

**To Reproduce**
1. Go to 'https://guru3.eventphone.de/extension.sql/my'
2. Click on 'Download invoice for rC3 – remote Chaos Experience'
3. Open the PDF

**Expected behavior**
"Page {{ current_page }} of undefined"

**Screenshots**
![image](https://user-images.githubusercontent.com/6574969/98727288-015ff880-2398-11eb-8c8c-a4c821f73561.png)

**Additional context**
Invoice is a great feature. 👍

**Comment by zivillian** [comment]
As far as we can see, the expected behavior looks exactly like the screenshot, but thanks for your feedback.
