### ISSUE TITLE
Provide the Phonebook in a JSON format

### ISSUE THREAD

**Issue by nervous-inhuman** [eventphone/guru3#23]
**Is your feature request related to a problem? Please describe.**
Guru2 used to provide the phonebook in a JSON format, this feature is absent from Guru3

**Describe the solution you'd like**
Implement an endpoint that responds with the Phonebook in JSON

**Describe alternatives you've considered**
Scraping the phonebook myself, but I'd like to avoid that... Eventphone LDAP doesn't include the "Type" attribute (e.g. SIP, DECT, Announcement), no clue about CalDAV.

**Comment by sur5r** [comment]
Just for clarification:

Do you want/need JSON output in particular is it just the missing type information that you need?

**Comment by nervous-inhuman** [comment]
I'd like the phonebook to be available as a JSON.

**Comment by zivillian** [comment]
I'm happy to announce that the GURU3 now officially supports json at https://guru3.eventphone.de/event.exe/gelbeseiten.json
