### ISSUE TITLE
Temporary disable membership in call group

### ISSUE THREAD

**Issue by saerdnaer** [eventphone/guru3#5]
**Is your feature request related to a problem? Please describe.**
As of now you can not temporary leave a call group when you are in your pause, as required by Engel-Gewerkschaft. :-)

**Describe the solution you'd like**
It would be nice, if one can disable/mute my own membership, and re-enable it later without the need to talk to one of the group administrators.

**Comment by saerdnaer** [comment]
Workaround: Give all members admin rights?

**Comment by garw** [comment]
implemented :)
