### ISSUE TITLE
Change of SIP Login when Extension changed.

### ISSUE THREAD

**Issue by psuet** [eventphone/guru3#6]
**Is your feature request related to a problem? Please describe.**
If you change your SIP-extension number in guru3 your credentials are subject to change.

**Describe the solution you'd like**
I would prefer a solution where each extension is assigned an arbitrary fixed (non-changing) Username and Password.

**Describe alternatives you've considered**
Leave as is.

**Comment by garw** [comment]
We have considered this while overhauling the overall routing and decided to leave it as it currently is. It would require an additional layer of indirection to the already complex call routing procedure. So I fear that you need to live with changing the SIP login name sometimes.
