### ISSUE TITLE
Callgroup Ringback Tone

### ISSUE THREAD

**Issue by MyIgel** [eventphone/guru3#7]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [...] configuring a callgroup and being unable to set the "Ich bin die Warteschleife" sound as a Ringback Tone :(

**Describe the solution you'd like**
Ringback Tones for callgroups!

**Describe alternatives you've considered**
This feature does not have an alternative approach

**Additional context**
`-`

**Comment by thomasDOTwtf** [comment]
Good news we decided to frickel ringbacktones for callgroups into the existing routing setup.
You might be able to use it at camp if testing in production works well ;)
