### ISSUE TITLE
DECT: Call forwarding when out of range

### ISSUE THREAD

**Issue by caev** [eventphone/guru3#8]
**Is your feature request related to a problem? Please describe.**
missed calls while leaving the event grounds for a group dinner

**Describe the solution you'd like**
GSM-like "call forwarding when not present" feature for DECT extensions, especially to EPVPN
 - forward calls before DECT extension is activated
 - forward calls when DECT extension is out-of-range
 - do not forward calls when DECT extension rings but isn't answered

**Describe alternatives you've considered**
alternative: just use SIP all the time.
why not: DECT has excellent reception, battery life, handset style, and fun factor.  SIP app situation is not fantastic.  mobile devices are distracting.

**Additional context**
These options used to exist in Alcatel Mobile Reflexes phones' menus, but they didn't work.

**Comment by garw** [comment]
About to come. New routing backend supports this. Call forwards in frontend are about to come.

**Comment by garw** [comment]
is configurable via guru now.
